apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.global.jobName }}
  namespace: {{ .Values.global.namespace }}
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.global.serviceaccount }}
      serviceAccount: {{ .Values.global.serviceaccount }}
      containers:
        - name: patcher
          image: {{ .Values.global.image }}
          command:
            - /bin/sh
            - -c
            - |
              set -xv    
              oc patch namespace {{ .Values.global.namespace }}  \
              --type=merge \
              -p '{
                "metadata": {
                "annotations": {
                "openshift.io/sa.scc.uid-range": "1000870000/10000",
                "openshift.io/sa.scc.supplemental-groups": "1000870000/10000",
                "openshift.io/sa.scc.mcs": "s0:c30,c0" }}}'
      restartPolicy: Never
