apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    annot4: value4
  labels:
    label2: value2
  name: ibm-lsr-console2
  namespace: reporter
spec:
  host: ibm-lsr-console2-reporter.apps.itz-q3xuba.infra01-lb.fra02.techzone.ibm.com
  path: /license-service-reporter
  port:
    targetPort: proxy
  tls:
    insecureEdgeTerminationPolicy: None
    termination: reencrypt
  to:
    kind: Service
    name: ibm-license-service-reporter2
    weight: 100
  wildcardPolicy: None
