global:
  namespaceReporter: reporter
  namespaceIls: ils
  jobName: ils-patch-job
  image: quay.io/openshift/origin-cli:latest
  serviceaccount: ibm-licensing-operator
  clusterID: ClusterTechzone
  clusterName: ClusterTechzone
  frequency: 0 */5 * * * *
  roleId: "8f5d296a-d06e-c9af-f9f3-87adbbe841f8"
  secretRef: vault-approle-creds
