apiVersion: v1
kind: Secret
metadata:
  name: vault-approle-creds
  namespace: {{ .Values.global.namespaceIls }}
type: Opaque
stringData:
  roleId: {{ .Values.vault.roleId }}
  {{ .values.vault.secretKey }} : 5b19736f-f95e-4390-30ec-c5e2a7614936
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-vault-backend
  namespace: {{ .Values.global.namespaceIls }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server }}
      path: {{ .Values.vault.secretStorePath }}
      version: "v2"
      auth:
        appRole:
          roleId: {{ .Values.vault.roleId }}
          secretRef:
            key: {{ .Values.vault.secretKey }}
            name: {{ .Values.vault.secretRef }}
      path: "secret"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ibm-license-service-reporter-token
  namespace: {{ .Values.global.namespaceIls }}
spec:
  refreshInterval: {{ .Values.vault.refreshInterval }}
  secretStoreRef:
    name: secretstore-vault-backend
    kind: SecretStore
  target:
    name: ibm-license-service-reporter-token
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: {{ .Values.vault.externalSecretPath }}
      property: token

